### ISSUE TITLE
Add support for package annotations

### ISSUE THREAD

**Issue by cjelger** [serverless/serverless-openwhisk#106]
When creating a package, one should be able to define package annotations like:

```
resources:
  packages:
    myPackage:
      parameters:
        hello: world
      annotations:
        name: value
        shared: true (or does it have to be named "publish" instead of "shared" ?)
```

This is particularly useful to create shared packages.
