### ISSUE TITLE
Support path parameters for APIGateway

### ISSUE THREAD

**Issue by csantanapr** [serverless/serverless-openwhisk#114]
Recently the CLI and Backend was updated to support path parameters

In CLI you would configure like
```
wsk api create /api /users/{id} get myWebAction --reponse-type http
```
I want to be able to configure same using serverless yml file
```
service: ibm-scala-sbt-cloud-function

provider:
  name: openwhisk
  runtime: java
  memory: 512
  timeout: 60
functions:
  hello:
    handler: target/scala-2.12/hello.jar:hello.Handler
    events:
      - http: 
          path: /api/hello/{id}
          method: get
          resp: http
          request:
            parameters:
              paths:
                id: true
plugins:
  - "serverless-openwhisk"
```
