### ISSUE TITLE
Add support for Composer actions

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-openwhisk#115]
Add a new kind for this:
https://github.com/apache/incubator-openwhisk/blob/fa624b96dbb2da60f85bb133caea01ca1b220108/docs/conductors.md

**Comment by jthomas** [comment]
This is already supported as conductors just rely on setting an annotation.

This configuration is the example from the documentation.

```yaml
service: conductor-test

provider:
  name: openwhisk

functions:
  triple:
    handler: triple.main
    name: triple
  increment:
    handler: increment.main
    name: increment
  tripleAndIncrement:
    handler: tripleAndIncrement.main
    name: tripleAndIncrement
    annotations:
      conductor: true

plugins:
  - serverless-openwhisk
```
