### ISSUE TITLE
Replicate binding service credentials to functions

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-openwhisk#122]
Available through `bx wsk service bind`

**Comment by jthomas** [comment]
This feature has now been implemented.

https://github.com/serverless/serverless-openwhisk#binding-services-ibm-cloud-functions

**Comment by jthomas** [comment]
@regmebaby absolutely, see example here:

```
functions:
  my_function:
    handler: file_name.handler    
    bind:
      - service:
          name: cloud-object-storage
          instance: my-cos-storage
      - service:
          name: another_service
          instance: my-instance-name
```

Couple of caveats... 
- you can't bind more than one instance of the same service (so no binding two instances of different object stores). 
- each service bind config shell outs to a separate CLI command run in sequence. if you have multiple service bindings shared between functions, put them onto a package to speed things up.
