### ISSUE TITLE
Specify package name as a value instead of key

### ISSUE THREAD

**Issue by volteanu** [serverless/serverless-openwhisk#140]
Currently, explicit (openwhisk) packages get their name from the object key. This prevents the user to parametrise the name, e.g. with variables. 

It would be very handy to accept a `name` property on the package, the same way it is currently for functions:

```yaml
resources:
  packages:
    myPackage:
      name: ${self:custom.packageName}
      parameters: ...
```
