### ISSUE TITLE
Parameter Value with -(dash) is not correctly deploying

### ISSUE THREAD

**Issue by yakalra1** [serverless/serverless-openwhisk#143]
we are doing a serverless deploy and passing parameter values to it..and one of the value starts with -(dash), reading from environment properties of Deploy Job.
But post deployment in parameters we see this value as true..rather than real value..

for eg - 
serverless deploy --CLOUDANT_API_KEY_VALUE $CLOUDANT_API_KEY where CLOUDANT_API_KEY  is like -khu1232we
And if i go to the parameters of my action, it shows value of CLOUDANT_API_KEY_VALUE as true.

I tried putting /(backslash) before the value with and without doublequotes, then it doesn't show true but adding some backslash.

**Comment by jthomas** [comment]
I'm unable to find where in the framework documentation this method of passing parameters is supported? 

Reading the docs on variables, setting the env parameter `CLOUDANT_API_KEY_VALUE` in the shell allows you to import it into the `serverless.yml` as follows...

```yml
service: example

provider:
  name: openwhisk

functions:
  hello:
    handler: handler.hello
    parameters:
      CLOUDANT_API_KEY: ${env:CLOUDANT_API_KEY}

plugins:
  - serverless-openwhisk
```

Does this fix your issue?
