### ISSUE TITLE
Specify explicit base path for http rules

### ISSUE THREAD

**Issue by volteanu** [serverless/serverless-openwhisk#145]
`serverless.yaml` allows to define (gateway) API mappings to functions in the form:
```
events:
    - http:
        path: /mypath
        method: get
        resp: http
```

Openwhisk has the concept of base path when creating the mappings, which groups them into one entity (api). Currently, `serverless` implies the basepath is `/${this.serverless.service.service}`.

My proposal is to add a field to the `http` event, called `basepath` which overrides the default. I can create a PR, but first I want to double check if that's ok.
