### ISSUE TITLE
Cannot read property 'packages' of undefined

### ISSUE THREAD

**Issue by michaelwclark** [serverless/serverless-openwhisk#150]
When doing a serverless deploy I get the error at the bottom of this issue. Even reverting to last working build results in the same thing. Iv'e tried different versions of serverless and other related modules with no luck. I can't see exactly where this is coming from so debugging is quite difficult. Any and all assistance would be appreciated.

```
    "serverless-openwhisk": "^0.16.1",
    "serverless-webpack": "^5.2.0",
```

serverless version:1.32.0

```

TypeError: Cannot read property 'packages' of undefined
    at OpenWhiskCompilePackages.renameManifestPackages (/usr/local/lib/node_modules/serverless-openwhisk/compile/packages/index.js:27:44)
From previous event:
    at PluginManager.invoke (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/Serverless.js:157:33)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless:43:50)
 ```

Serverless.yml
```
service: denim-graph

provider:
  name: openwhisk
  runtime: nodejs:8


functions:
  graphql:
    name: graphql
    handler: src/controllers/denim-graph/denim-graph.denimGraph
    overwrite: true
    memory: 512
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    events:
      - http: POST /api/graphql
      - http: GET /api/graphql
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      OW_API_HOST: ${env:OW_API_HOST}
      OW_API_KEY: ${env:OW_API_KEY}
      OW_NAMESPACE: ${env:OW_NAMESPACE}
      RAVEN_DSN: ${env:RAVEN_DSN}
  build-denim-fb-campaign:
    name: build-denim-fb-campaign
    handler: src/controllers/facebook/campaign/denim-fb-campaign.startBuildProcess
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    events:
      - http: POST /api/build-fb-campaign
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      OW_API_HOST: "${env:OW_API_HOST}"
      OW_API_KEY: "${env:OW_API_KEY}"
      OW_NAMESPACE: "${env:OW_NAMESPACE}"
      RAVEN_DSN: ${env:RAVEN_DSN}
  build-denim-fb-targeting:
    name: build-denim-fb-targeting
    handler: src/controllers/facebook/targeting/denim-fb-targeting.buildAdSetTargeting
    overwrite: true
  build-denim-fb-creative:
    name: build-denim-fb-creative
    handler: src/controllers/facebook/creative/denim-fb-creative.buildFbCreative
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      OW_API_HOST: "${env:OW_API_HOST}"
      OW_API_KEY: "${env:OW_API_KEY}"
      OW_NAMESPACE: "${env:OW_NAMESPACE}"
      RAVEN_DSN: ${env:RAVEN_DSN}
  build-denim-fb-adset:
    name:  build-denim-fb-adset
    handler: src/controllers/facebook/adset/denim-fb-adset.startBuildProcess
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      OW_API_HOST: "${env:OW_API_HOST}"
      OW_API_KEY: "${env:OW_API_KEY}"
      OW_NAMESPACE: "${env:OW_NAMESPACE}"
      RAVEN_DSN: ${env:RAVEN_DSN}
  build-denim-fb-ad:
    name:  build-denim-fb-ad
    handler: src/controllers/facebook/ad/denim-fb-ad.startBuildFacebookAdProcess
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      OW_API_HOST: "${env:OW_API_HOST}"
      OW_API_KEY: "${env:OW_API_KEY}"
      OW_NAMESPACE: "${env:OW_NAMESPACE}"
      RAVEN_DSN: ${env:RAVEN_DSN}  
  update-fb-insights:
    name: update-fb-insights
    handler: src/controllers/facebook/insights/entry/denim-fb-insights-entry.pollCampaignsAndDispatchInsightsActions
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      OW_API_HOST: "${env:OW_API_HOST}"
      OW_API_KEY: "${env:OW_API_KEY}"
      OW_NAMESPACE: "${env:OW_NAMESPACE}"
      RAVEN_DSN: ${env:RAVEN_DSN}
    events:
      - schedule:
          rate: cron(0 * * * *) // call once an hour
  update-facebook-campaign-insights:
    name: update-facebook-campaign-insights
    handler: src/controllers/facebook/insights/campaign/denim-fb-campaign-insights.fetchNewDenimCampaignInsights
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}
  update-facebook-ad-insights:
    name: update-facebook-ad-insights
    handler: src/controllers/facebook/insights/ad/denim-fb-ad-insights.fetchNewDenimAdInsights
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}
  update-facebook-adset-insights:
    name: update-facebook-adset-insights
    handler: src/controllers/facebook/insights/adset/denim-fb-adset-insights.fetchNewDenimAdsetInsights
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}
  denim-fb-budget-reallocation:
    name: denim-fb-budget-reallocation
    handler: src/controllers/facebook/reallocation/denim-fb-budget-reallocation.pollCampaignsForReallocation
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}
    events:
      - schedule:
          rate: cron(0 * * * *) // call once an hour
  reallocate-facebook-adsets:
    name: reallocate-facebook-adsets
    handler: src/controllers/facebook/reallocation/reallocate-facebook-adsets.startReallocation
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}
  denim-painted-door-entry:
    name: denim-painted-door-entry
    handler: src/controllers/painted-door/painted-door.paintedDoorEntry
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    events:
      - http: POST /api/painted-door
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}
  get-fb-ad-preview:
    name: get-fb-ad-preview
    handler: src/controllers/facebook/preview/denim-fb-preview.getFacebookAdPreivew
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}      
  update-denim-fb-campaign:
    name: update-denim-fb-campaign
    handler: src/controllers/facebook/campaign/update-campaign/update-denim-fb-campaign.updateDenimFbCampaign
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}    
  delete-denim-campaign:
    name: delete-denim-campaign
    handler: src/controllers/facebook/campaign/delete-campaign/delete-campaign.deleteDenimCampaign
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}    
  send-mail:
    name: send-mail
    handler: src/controllers/send-mail/denim-send-mail.sendMail
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN}        
      MAIL_FROM: "xxx"
      MAIL_PASS: ${env:MAIL_PASS}
  send-insights-link:
    name: send-insights-link
    handler: src/controllers/send-insights-link/send-insights-link.sendInsightsLink
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN} 
  generate-periodic-insights:
    name: generate-periodic-insights
    handler: src/controllers/periodic-insights/periodic-insights.generatePeriodicInsights
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN} 
    events:
      - schedule:
          rate: cron(0 */6 * * *) // call once every 6 hours
  capture-ad-lead:
    name: capture-ad-lead
    handler: src/controllers/ad-leads/ad-leads.captureAdLead
    overwrite: true
    annotations:
      web-export: true
      require-whisk-auth: ${env:OW_HEADER_AUTH}
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}
      RAVEN_DSN: ${env:RAVEN_DSN} 

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-openwhisk
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true    # Node modules configuration for packaging

package:
  individually: true
  exclude:
    - .spec.js
```
