### ISSUE TITLE
Message Hub trigger doesn't fire

### ISSUE THREAD

**Issue by pheuberger** [serverless/serverless-openwhisk#163]
I'm running serverless via IBM Cloud Functions.
Here are the relevant parts from my `serverless.yml` file:
```
custom:
  org: MyOrg
  space: ${env:SPACE}
  mhServiceName: MyOrg-kafka

functions:
  main:
    handler: src/handler.main
    bind:
      - service:
          name: messagehub
          instance: ${self:custom.mhServiceName}
    events:
      - message_hub:
          package: /${self:custom.org}_${self:custom.space}/Bluemix_${self:custom.mhServiceName}_Credentials-1
          topic: sales
```

Running the deploy script it indeed creates a trigger for this topic. However the function is not invoked when messages are published to this topic.
In turn, when I create a trigger through the IBM Cloud Console and connect it to my function it works. 

I noticed, serverless creates a `Custom Trigger` whereas creating a trigger via the Cloud Console gives you a `Message Hub` trigger. Might this have something to do with it?

<img width="1137" alt="Screen Shot 2019-03-26 at 2 33 47 PM" src="https://user-images.githubusercontent.com/16206423/55001554-1e826080-4fd5-11e9-83ac-18d028a818c0.png">
