### ISSUE TITLE
Namespace deployment fails

### ISSUE THREAD

**Issue by benoj** [serverless/serverless-openwhisk#182]
Whenever I try to deploy my functions to a namespace i get an error saying my account is not authorized. However my account is the administrator account. Works fine when using default environment.

serverless.yml
```
service: asset-registry

provider:
  name: openwhisk
  namespace: 'environment_dev'
  
functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /hello

plugins:
  - serverless-openwhisk

```

```
Failed to deploy function (asset-registry-dev-hello) due to error: PUT https://eu-gb.functions.cloud.ibm.com/api/v1/namespaces/environment_dev/actions/asset-registry-dev-hello?ov
erwrite=true Returned HTTP 403 (Forbidden) --> "The supplied authentication is not authorized to access 'environment_dev/asset-registry-dev-hello'."

```
