### ISSUE TITLE
Service information adds extra `https://` for every endpoint

### ISSUE THREAD

**Issue by marcinczeczko** [serverless/serverless-openwhisk#189]
Once web-action is deployed, the service information shows endpoints with redundant schema (extra `https://`)

![image](https://user-images.githubusercontent.com/4218395/77536493-b04cd400-6e9c-11ea-9422-2dd9d5a60ab9.png)

How to reproduce
- Follow the sls openwhisk quickstart but made an action a web-action
```
functions:
  hello:
    handler: handler.hello
    annotations:
      web-export: true
```
- Deploy to openwhisk
