### ISSUE TITLE
Support HTTP event object parameter 

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-openwhisk#25]
This implementation currently supports the HTTP event in the following format.

```
events:
  - http: GET some/path
```

It does not support the secondary style that AWS Lambda's implementation also supports.

```
events:
  - http: 
    path: some/path
    method: GET
```

This implementation should be updated to support this.
