### ISSUE TITLE
Exception when deploying Message Hub trigger

### ISSUE THREAD

**Issue by shawdm** [serverless/serverless-openwhisk#37]
Deploying a Message Hub trigger:

```
resources:
  triggers:
    sm-message-hub-incoming:
      parameters:
      feed: /whisk.system/messaging/messageHubFeed
      feed_parameters:
        endpoint: openwhisk.ng.bluemix.net
        kafka_brokers_sasl: '["kafka01-prod02.messagehub.services.eu-gb.bluemix.net:9093", "kafka02-prod02.messagehub.services.eu-gb.bluemix.net:9093", "kafka03-prod02.messagehub.services.eu-gb.bluemix.net:9093" ,"kafka04-prod02.messagehub.services.eu-gb.bluemix.net:9093", "kafka05-prod02.messagehub.services.eu-gb.bluemix.net:9093"]'
        kafka_admin_url: https://kafka-admin-prod02.messagehub.services.eu-gb.bluemix.net:443
        isJSONData: true
        topic: kb-tweets
        user: ${env:KAFKA_USER}
        password: ${env:KAFKA_PASSWORD}
        api_key: ${env:KAFKA_API_KEY}
```

Causes the following exception:
```
ServerlessError: Failed to deploy feed (messaging/messageHubFeed) due to error: Invalid URL for API called, OpenWhisk returned HTTP 404 response. The requested resource does not exist.
    at ow.feeds.create.catch.err (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/deploy/lib/deployFeeds.js:19:15)
    at tryCatcher (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/shawdm/Documents/Projects/kappa-bluemix/code/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:160:22)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:91:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Trying to put some debug information in ```deployFeeds.js``` I changed the deployFeed method to
```
deployFeed(feed) {
    return this.provider.client().then(function(ow){
      ow => ow.feeds.create(feed).catch(err => {
        throw new this.serverless.classes.Error(
          `Failed to deploy feed (${feed.feedName}) due to error: ${err.message}`
        );
      })
    });
  }
```

...so I could add some logging.  Adding the normal function rather than the big arrow one seems to make it work, or at least not throw any exceptions, but I can't understand why.  I'm sure this is my lack of understanding the big arrow function.
