### ISSUE TITLE
http POST event is no longer working

### ISSUE THREAD

**Issue by lynnaloo** [serverless/serverless-openwhisk#56]
This event was working previously, but when I tried to deploy to a different environment it no longer worked. `GET` seems to be fine, but the resulting `POST` uri doesn't execute my action.

```
functions:
  processImage:
    handler: handler.imageLabels
    events:
      - http:
          path: /analyse/image
          method: post
```
