### ISSUE TITLE
Deploying API Gateway definitions... 401

### ISSUE THREAD

**Issue by JohnCoding94** [serverless/serverless-openwhisk#61]
I am trying to deploy a basic function with an HTTP trigger, but it looks like my token is not recognized:

```
Serverless: Packaging service...
Serverless: Compiling Functions...
Serverless: Compiling API Gateway definitions...
Serverless: Compiling Rules...
Serverless: Compiling Triggers & Feeds...
Serverless: Deploying Functions...
Serverless: Deploying API Gateway definitions...
 
  Serverless Error ---------------------------------------
 
  Failed to deploy API Gateway route (home) due to error: POST https://openwhisk.ng.bluemix.net/api/v1/web/whisk.system/apimgmt/createApi.http Returned HTTP 502 (Bad Gateway) --> "API creation failure: Unable to obtain API(s) from the API Gateway (status code 401): {"error":{"statusCode":401,"message":"Unauthorized"}}"
```

Here are the commands i have exucuted (i copy/paste all values from my ~/.wskprops file):

```
export OW_AUTH=<my-key-here>
export OW_APIHOST=<my-api-host>
export OW_APIGW_ACCESS_TOKEN=<my-access-token>
serverless deploy
```

Do you know why?

I am using serverless-openwhisk@0.7.0 and serverless@1.15.3.

My serverless.yml is:

```
provider:
  name: openwhisk

functions:
  hello:
    name: ${opt:stage}-test
    environment:
      NODE_ENV: ${opt:stage}
    handler: handler.hello
    events:
      - http:
          method: get
          path: home

plugins:
  - serverless-openwhisk
```
