### ISSUE TITLE
How can I set a environment variable/secret?

### ISSUE THREAD

**Issue by gabrielperales** [serverless/serverless-openwhisk#64]
I'm trying to use an environment variable inside my function, but when I run muy function it is `undefined`. I've tried with this `serverless.yml`:

```yml
service: serverless-slack-jobs

provider:
  name: openwhisk

functions:
  scrape:
    handler: handler.scrape
    events:
      - schedule: cron(0 10 * * *) # run every day at 10am
    environment:
       SLACK_WEBHOOK: ${file(serverless.env.yml:SLACK_WEBHOOK}
plugins:
      - serverless-openwhisk
```

and this is what I have inside `serverless.env.yml`:

```yml
dev:
  SLACK_WEBHOOK: 'https://hooks.slack.com/services/********'
```

and this is my `handler.js`:
```javascript
module.exports.scrape = () => {
  console.log(`SLACK_WEBHOOK: ${process.env.SLACK_WEBHOOK}`);
};
```

**Comment by jthomas** [comment]
Hello @gabrielperales 👋. Thanks for raising an issue with all the context on your problem.

OpenWhisk does not support using environment variables to pass custom parameters into the actions. Instead, of using environment variables, you can use *default parameters* on actions.

Default parameters can be defined when you create or update an action. The platform stores these parameters internally and automatically includes them in the invocations parameters.

This is a simple fix for your application manifest...

```yml
service: serverless-slack-jobs

provider:
  name: openwhisk

functions:
  scrape:
    handler: handler.scrape
    events:
      - schedule: cron(0 10 * * *) # run every day at 10am
    parameters:
       SLACK_WEBHOOK: ${file(serverless.env.yml:SLACK_WEBHOOK}
plugins:
      - serverless-openwhisk
```

and then in your handler function, you can access the webhook URL through the invocation parameters.

and this is my `handler.js`:

```javascript
module.exports.scrape = params => {
  console.log(`SLACK_WEBHOOK: ${params.SLACK_WEBHOOK}`);
};
```
