### ISSUE TITLE
Handler parsing fails for dots in path

### ISSUE THREAD

**Issue by herzog31** [serverless/serverless-openwhisk#65]
If I specify a function like this

```yaml
myFunction:
    name: myFunction
    handler: myFunction@0.1.0/index.main
    package:
      include:
        - myFunction@0.1.0/**
```

I get the following error

`Function handler (myFunction@0.js) does not exist.`.

My folder structure looks like this:
```
./myFunction@0.1.0
./myFunction@0.1.0/index.js
./serverless.yml
```
