### ISSUE TITLE
Relative paths for actions are not correctly packaged

### ISSUE THREAD

**Issue by herzog31** [serverless/serverless-openwhisk#69]
Using relative paths like in the following example fails, because

* `calculateFunctionMain()` is not able to determine the main function correctly. 
* The relative path is not correctly resolved in `generateActionPackage()`, so it stays relative in the generated `package.json` file which is incorrect.

```yaml
myFunction:
    name: myFunction
    handler: ../myFunction/index.main
    package:
      include:
        - ../myFunction/**
```

The folder structure would look like this:
```
./myFunction
./myFunction/index.js
./deployment/serverless.yml
```

This issue is partially related to #65.
