### ISSUE TITLE
Support multiple stages

### ISSUE THREAD

**Issue by maxfrigge** [serverless/serverless-openwhisk#72]
I cannot figure a way to deploy to multiple stages/environments. If I am not mistaken, there is stage property for AWS that takes care of this. 

What I would like to achieve are two API endpoints to point at different versions of the same handler - e.g. staging and production. I tried adding a prefix to the http event route, but it gets overwritten each time a function with the same name is deployed. 

Is this currently not supported or am I am missing something?

**Comment by jthomas** [comment]
Hello @maxfrigge, let me try this out and see what's going wrong... 

OpenWhisk doesn't have a built-in concept of "stages" like AWS Lambda. I've chosen to simulate this behaviour by putting the stage in the function name.

**Comment by jthomas** [comment]
I've been experimenting. Is what you're looking for?

```
service: stage-apis

provider:
   name: openwhisk

functions:
  hello:
    handler: handler.hello
    events:
       - http: GET /api/${opt:stage}

plugins:
  - serverless-openwhisk
```

If I type `serverless deploy -s  prod|dev` I get different functions with separate API endpoints.
