### ISSUE TITLE
Add new Cloudant feed parameters to event

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-openwhisk#74]
[Cloudant trigger feed](https://github.com/apache/incubator-openwhisk-package-cloudant) also supports the following parameters.

* `filter`
* `query_params`
* `maxTriggers`

These values need to be added the `feed_parameters` if present in YAML file [here](https://github.com/serverless/serverless-openwhisk/blob/master/compile/cloudant/index.js#L53-L69). 

Want to be able to support this YAML example...

```yaml
functions:
    index:
        handler: users.main
        events:
            - cloudant:          
                max: 10000 // maxTriggers
                query: // object YAML config
                   status: new
                filter: mailbox/by_status
```
