### ISSUE TITLE
How to enable --web raw

### ISSUE THREAD

**Issue by allansduarte** [serverless/serverless-openwhisk#86]
Hello!

I am looking for guidelines to enable raw http processing on serverless.
`wsk action create /guest /demo /hello hello.js --web raw`

I am currently aware of the possibility of enabling a web action `with web-exports: true`
`--web true`

But not raw http:
`--web raw`

Is there such a possibility nowadays?

**Comment by jthomas** [comment]
This is possible. 👏👏👏.

According to this docs, `raw` sets the following two annotations: `web-export` and `raw-http`. 
https://github.com/apache/incubator-openwhisk/blob/master/docs/annotations.md#annotations-specific-to-web-actions

This can be achieved with the following `serverless.yml`

```yml
functions:
  my_function:
    handler: index.main
    annotations:
      web-export: true
      raw-http: true
```

Does that help?
