### ISSUE TITLE
Add support for creating actions under custom package

### ISSUE THREAD

**Issue by bryantsai** [serverless/serverless-openwhisk#87]
Packages can be useful for defining default parameters for all actions in it.

**Comment by jthomas** [comment]
Packages can be used by setting the `name` property on the functions.

```
functions:
  hello:
    name: testing/package-hello
    handler: handler.hello
```

This should be better documented. I'll leave this ticket open till I fix that.

There is a [longer-term plan to use packages to each service](https://github.com/serverless/serverless-openwhisk/issues/29) but that's blocked on a platform issue.
